# Generated by Django 3.1 on 2020-10-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
