# Generated by Django 3.1 on 2020-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201019_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
