# Generated by Django 3.1 on 2020-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201019_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=70)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
            ],
        ),
    ]
