# Generated by Django 3.1 on 2020-10-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201024_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=100)),
                ('full_desc', models.CharField(max_length=400)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.shop')),
            ],
        ),
    ]
