# Generated by Django 3.1 on 2020-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shopdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='full_desc',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='shopdetails',
            name='short_desc',
            field=models.TextField(max_length=100),
        ),
    ]
